export const bookData = [
  {
    id: 1,
    name: "To Kill a Mockingbird",
    description:
      "A novel of warmth and humor, it explores racial injustice, moral growth, and the loss of innocence in the Deep South, seen through the eyes of a young girl.",
    url: "https://covers.openlibrary.org/b/id/12907439-L.jpg",
    printLength: 336,
    language: "English",
    author: "Harper Lee",
    price: 399,
    genre: "Fiction",
  },
  {
    id: 2,
    name: "1984",
    description:
      "A dystopian masterpiece about surveillance, censorship, and totalitarianism, where the protagonist, Winston Smith, struggles against the oppressive regime led by Big Brother.",
    url: "https://covers.openlibrary.org/b/id/14656453-L.jpg",
    printLength: 328,
    language: "English",
    author: "George Orwell",
    price: 299,
    genre: "Dystopian, Science Fiction",
  },
  {
    id: 3,
    name: "The Great Gatsby",
    description:
      "Set in the Roaring Twenties, this novel delves into themes of love, wealth, and the American Dream, as Jay Gatsby strives to win back the heart of Daisy Buchanan.",
    url: "https://covers.openlibrary.org/b/id/12364437-L.jpg",
    printLength: 180,
    language: "English",
    author: "F. Scott Fitzgerald",
    price: 349,
    genre: "Classic, Romance",
  },
  {
    id: 4,
    name: "Pride and Prejudice",
    description:
      "This timeless novel portrays the life of Elizabeth Bennet as she navigates love, societal expectations, and personal growth while dealing with her strong-willed yet charming suitor, Mr. Darcy.",
    url: "https://covers.openlibrary.org/b/id/13440880-L.jpg",
    printLength: 279,
    language: "English",
    author: "Jane Austen",
    price: 450,
    genre: "Romance, Classic",
  },
  {
    id: 5,
    name: "The Catcher in the Rye",
    description:
      "A rebellious teenager named Holden Caulfield shares his thoughts on society, alienation, and growing up, all while struggling with depression and a search for authenticity in a world full of phoniness.",
    url: "https://covers.openlibrary.org/b/id/14318932-L.jpg",
    printLength: 277,
    language: "English",
    author: "J.D. Salinger",
    price: 325,
    genre: "Fiction, Bildungsroman",
  },
  {
    id: 6,
    name: "The Hobbit",
    description:
      "Bilbo Baggins, an unlikely hero, embarks on an extraordinary adventure with a group of dwarves to reclaim a treasure guarded by the fearsome dragon Smaug, in this prelude to The Lord of the Rings.",
    url: "https://covers.openlibrary.org/b/id/14627222-L.jpg",
    printLength: 310,
    language: "English",
    author: "J.R.R. Tolkien",
    price: 499,
    genre: "Fantasy, Adventure",
  },
  {
    id: 7,
    name: "Little Women",
    description:
      "Set during the Civil War, this beloved classic follows the lives of the four March sisters as they navigate hardships, personal growth, love, and sacrifice, finding their way to womanhood.",
    url: "https://covers.openlibrary.org/b/id/10615618-L.jpg",
    printLength: 759,
    language: "English",
    author: "Louisa May Alcott",
    price: 600,
    genre: "Historical Fiction, Drama",
  },
  {
    id: 8,
    name: "The Alchemist",
    description:
      "This philosophical novel follows the journey of Santiago, a young shepherd, as he travels from Spain to Egypt in search of treasure, learning about life's purpose and the importance of following one's dreams along the way.",
    url: "https://covers.openlibrary.org/b/id/14828473-L.jpg",
    printLength: 208,
    language: "English",
    author: "Paulo Coelho",
    price: 250,
    genre: "Adventure, Philosophy",
  },
  {
    id: 9,
    name: "Harry Potter and the Sorcerer’s Stone",
    description:
      "The first book in the iconic Harry Potter series introduces Harry, a young wizard who discovers his true identity and attends Hogwarts, where he faces challenges and uncovers dark secrets about his past.",
    url: "https://covers.openlibrary.org/b/id/14656853-L.jpg",
    printLength: 320,
    language: "English",
    author: "J.K. Rowling",
    price: 399,
    genre: "Fantasy, Adventure",
  },
  {
    id: 10,
    name: "The Kite Runner",
    description:
      "A poignant story of friendship, betrayal, and redemption set against the backdrop of Afghanistan's political turmoil, as Amir seeks to make amends for betraying his childhood friend, Hassan.",
    url: "https://covers.openlibrary.org/b/id/12641921-L.jpg",
    printLength: 372,
    language: "English",
    author: "Khaled Hosseini",
    price: 349,
    genre: "Historical Fiction, Drama",
  },
  {
    id: 11,
    name: "The Road",
    description:
      "In a desolate, post-apocalyptic world, a father and son journey across a ravaged America, holding onto hope and love as they strive for survival and search for any remnants of humanity.",
    url: "https://covers.openlibrary.org/b/id/14818120-L.jpg",
    printLength: 287,
    language: "English",
    author: "Cormac McCarthy",
    price: 299,
    genre: "Post-Apocalyptic, Fiction",
  },
  {
    id: 12,
    name: "The Book Thief",
    description:
      "Set in Nazi Germany, this novel tells the story of Liesel, a young girl who finds solace in stealing books and sharing them with others, while Death narrates the tale of love, loss, and resilience in wartime.",
    url: "https://covers.openlibrary.org/b/id/12915081-L.jpg",
    printLength: 552,
    language: "English",
    author: "Markus Zusak",
    price: 550,
    genre: "Historical Fiction, War",
  },
  {
    id: 13,
    name: "Life of Pi",
    description:
      "Pi Patel’s incredible journey of survival across the Pacific Ocean with a Bengal tiger named Richard Parker explores faith, spirituality, and the strength of the human spirit in the face of overwhelming odds.",
    url: "https://covers.openlibrary.org/b/id/7258954-L.jpg",
    printLength: 319,
    language: "English",
    author: "Yann Martel",
    price: 375,
    genre: "Adventure, Fiction",
  },
  {
    id: 14,
    name: "The Da Vinci Code",
    description:
      "A fast-paced thriller that follows Robert Langdon and Sophie Neveu as they uncover hidden messages in famous works of art, unraveling mysteries surrounding the Holy Grail and the legacy of secret societies.",
    url: "https://covers.openlibrary.org/b/id/12392336-L.jpg",
    printLength: 489,
    language: "English",
    author: "Dan Brown",
    price: 450,
    genre: "Thriller, Mystery",
  },
  {
    id: 15,
    name: "The Silent Patient",
    description:
      "A psychological thriller about Alicia Berenson, a famous painter who is accused of murdering her husband and then falls silent. A psychotherapist becomes obsessed with unraveling the mystery behind her silence.",
    url: "https://covers.openlibrary.org/b/id/8415060-L.jpg",
    printLength: 325,
    language: "English",
    author: "Alex Michaelides",
    price: 400,
    genre: "Thriller, Mystery",
  },
  {
    id: 16,
    name: "The Midnight Library",
    description:
      "Nora Seed finds herself in a magical library, where each book represents a different life she could have lived. She embarks on a journey to explore the alternate versions of her life, in search of happiness and fulfillment.",
    url: "https://covers.openlibrary.org/b/id/14825926-M.jpg",
    printLength: 304,
    language: "English",
    author: "Matt Haig",
    price: 370,
    genre: "Fantasy, Fiction",
  },
  {
    id: 17,
    name: "A Man Called Ove",
    description:
      "Ove is a grumpy yet lovable old man who finds unexpected connections with his neighbors. Through heartwarming interactions, he discovers that life can still hold joy and meaning, even in the later years.",
    url: "https://covers.openlibrary.org/b/id/12868311-L.jpg",
    printLength: 337,
    language: "English",
    author: "Fredrik Backman",
    price: 340,
    genre: "Fiction, Drama",
  },
  {
    id: 18,
    name: "Sapiens: A Brief History of Humankind",
    description:
      "Yuval Noah Harari explores the history of humankind, from the emergence of Homo sapiens in Africa to the modern-day challenges of artificial intelligence, exploring the forces that shaped our societies and our future.",
    url: "https://covers.openlibrary.org/b/id/9137127-L.jpg",
    printLength: 498,
    language: "English",
    author: "Yuval Noah Harari",
    price: 550,
    genre: "Non-fiction, History",
  },
  {
    id: 19,
    name: "Becoming",
    description:
      "Michelle Obama’s deeply personal memoir reflects on her journey from her childhood in Chicago to the White House, offering insights into her life, values, and the struggles she faced along the way.",
    url: "https://covers.openlibrary.org/b/id/8565814-L.jpg",
    printLength: 448,
    language: "English",
    author: "Michelle Obama",
    price: 450,
    genre: "Biography, Non-fiction",
  },
  {
    id: 20,
    name: "Atomic Habits",
    description:
      "In *Atomic Habits*, James Clear outlines the power of small, incremental changes and how they can lead to remarkable transformations. Through scientific research and practical strategies, he explains how habits work, how to build good ones, and break bad ones, providing a step-by-step guide to creating lasting change.",
    url: "https://covers.openlibrary.org/b/id/14830739-L.jpg",
    printLength: 320,
    language: "English",
    author: "James Clear",
    price: 399,
    genre: "Self-help, Non-fiction",
  },
];

export default bookData;
